version: '3.8'

services:
  postgres:
    image: hub.hamdocker.ir/postgres:16-alpine
    container_name: gofo_postgres
    env_file:
      - env_samples/.env.postgres
    volumes:
      - type: volume
        source: gofo_postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500M

volumes:
  gofo_postgres_data: