DROP TABLE IF EXISTS invoices_edibles
DROP TABLE IF EXISTS menus_edibles
DROP TABLE IF EXISTS invoices
DROP TABLE IF EXISTS menus
DROP TABLE IF EXISTS edibles
DROP TABLE IF EXISTS restaurants
DROP TABLE IF EXISTS users

